version: "3.3"
services:

  ui:
    container_name: ml-blocks-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ml-net

volumes:
  store-data-volume: null

networks:
  ml-net:
