version: "3.3"
services:

  ml_blocks_root:
    volumes:
      - ./samples/ml-blocks:/app
      - ./samples/stores/default:/app/data
    build:
      context: ./samples/ml-blocks
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    environment:
      - LOADER=pandas
    ports:
      - "9080:80"
    command: ["/app/start.sh"]
    networks:
        - ml-blocks-net

  ui:
    depends_on:
      - ml_blocks_root
    container_name: ml-blocks-ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    links:
      - "ml_blocks_root:ml_blocks_root"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ROOT_HOST=ml_blocks_root
    networks:
      - ml-blocks-net

volumes:
  store-data-volume: null

networks:
  ml-blocks-net:
    driver: bridge